#! /usr/bin/env bash

# =============================================================================
#
#   name:   volume
#   auth:   ted craig
#
#   desc:   Adjusts the volume settings on MacOs.
#
#   dependancies: ttui_lib.sh
#
# =============================================================================

# -----------------------------------------------------------------------------
# Global Vars
# -----------------------------------------------------------------------------
readonly FULL_PATH_TO_SCRIPT="$(which "$0")"
readonly PATH_TO_SCRIPT="$(dirname "$0")"
readonly BASENAME="$(basename "$0")"


# -----------------------------------------------------------------------------
# Imports
# -----------------------------------------------------------------------------
# source "${PATH_TO_SCRIPT}"'/ttui_lib.sh'
source /opt/ttui/ttui_lib.sh

main() {
  
  # echo "${FULL_PATH_TO_SCRIPT}"
  # echo "basename \$0: $(basename "$0")"
  # echo "dirname \$0: $(dirname "$0")"

  [[ $# -lt 1 ]] && {
    echo "Usage: "
    echo "  volume [0-100]"
    echo "  sets system volume to specified percentage"
    exit 0
  }

  if (( $1 >= 0 )) && (( $1 <= 100 )); then
    # osascript examples:
    #   Set the output volume to 50%
    #     sudo osascript -e 'set volume output volume 50'
    #   Input volume and Alert volume can also be set from 0 to 100%:
    #     sudo osascript -e 'set volume input volume 40'
    #     sudo osascript -e 'set volume alert volume 75'
    osascript -e "set volume output volume $1"
  else
    echo "invalid arg '$1': must be integer in range 0 thru 100"
  fi  
  

}


main "$@"